server:
  port: 10002
spring:
  profiles:
    active: dev
  application:
    name: JFRAME-SERVICE-ORDER
info:
  app:
    name: ${spring.application.name}
    version: "1.0"
    description: "service-order"
app:
  eureka:
    enabled: true
  monitor:
    enabled: true
  db:
    db1:
      enabled: true
