server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: JFRAME-WEB-MANAGE
info:
  app:
    name: ${spring.application.name}
    version: "1.0"
    description: "manage"
app:
  pro:
    appkey: ""
    static_path: /data/wwwroot/manage/static/
    static_host: http://192.168.1.199:${server.port}/
  db:
    db1:
      enabled: true