server:
  port: 8080
spring:
  profiles:
    active: dev
  session:
    store-type: none
  application:
    name: JFRAME-WEB-MANAGE
management:
  security:
    enabled: true
  port: 9090
  context-path: /monitor
security: # spring安全设置
  basic:
    enabled: true
    path: /monitor # 需要配置安全的路径
  user: # 用户名和密码
    name: cloud
    password: cloud1234
endpoints: # Actuator监控，可自定义端点的开关-enabled
  enabled: false
info:
  app:
    name: ${spring.application.name}
    version: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka1234@127.0.0.1:10000/eureka/