server:
  port: 8080
spring:
  profiles:
    active: dev
  session:
    store-type: none
  application:
    name: JFRAME-WEB-MANAGE
management:
  security:
    enabled: false
  port: 9090
  context-path: /monitor
security:
  basic:
    enabled: false
    path: /monitor
  user:
    name: cloud
    password: cloud1234
endpoints:
  enabled: false
info:
  app:
    name: ${spring.application.name}
    version: 1.0
    description: "manage"
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://eureka:eureka1234@127.0.0.1:10000/eureka/
app:
  pro:
    appkey: ""
    path: /data/wwwroot/manage/static/
    host: http://192.168.1.199:${server.port}/
  scheduler:
    enabled: true