server:
  port: 9201
spring:
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  data: # es配置
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: dev:9300
      repositories:
        enabled: true
logging:
  level:
    root: info