version: '3'
services:
  es11:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: es11
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata11:/usr/share/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

  es12:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: es12
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es11"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata12:/usr/share/elasticsearch

  es13:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: es13
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es11"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata13:/usr/share/elasticsearch

volumes:
  esdata11:
    driver: local
  esdata12:
    driver: local
  esdata13:
    driver: local

networks:
  default:
    external:
      name: es