auth-server: http://127.0.0.1:8090
local-server: http://127.0.0.1:8092
server:
  port: 8092
  servlet:
    context-path: /
    session:
      cookie:
        name: JSAUID2 # 每个客户端的Cookie值必须唯一
security:
  oauth2:
    sso:
      login-path: /sso/login
    client:
      client-id: sso02
      client-secret: 123456
      user-authorization-uri: ${auth-server}/oauth/authorize
      access-token-uri: ${auth-server}/oauth/token
    resource:
      user-info-uri: ${auth-server}/authentication/user
logging:
  level:
    org.springframework: info