auth-server: http://192.168.24.200:8090
local-server: http://192.168.1.129:8091
server:
  port: 8091
  servlet:
    context-path: /
    session:
      cookie:
        name: JSAUID1 # 每个客户端的Cookie值必须唯一
spring:
  session:
    store-type: redis
    timeout: 5m
    redis:
      namespace: session:sso
  redis:
    host: dev
    port: 6379
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
security:
  oauth2:
    sso:
      login-path: /sso/login
    client:
      client-id: sso01
      client-secret: 123456
      user-authorization-uri: ${auth-server}/oauth/authorize
      access-token-uri: ${auth-server}/oauth/token
    resource:
      user-info-uri: ${auth-server}/authentication/user
logging:
  level:
    org.springframework: info