server:
  port: 8082
spring:
  profiles:
    active: dev
  application:
    name: JFRAME-WEB-APP
info:
  app:
    name: ${spring.application.name}
    version: "1.0"
    description: "app"
app:
  appkey: 00056cb1d74435076a4c15a490798df4
  static_path: /data/wwwroot/app/static/
  static_host: http://192.168.1.199:8082/
  cache:
    enabled: true