server:
  port: 8082
spring:
  profiles:
    active: dev
  application:
    name: JFRAME-WEB-APP
info:
  app:
    name: ${spring.application.name}
    version: "1.0"
    description: "app"
app:
  pro:
    appkey: 00056cb1d74435076a4c15a490798df4
    static_path: /data/wwwroot/app/static/
    static_host: http://192.168.1.199:${server.port}/
  db:
    db1:
      enabled: true