server:
  port: 8082
spring:
  profiles:
    active: dev
  session:
    store-type: none
  application:
    name: JFRAME-WEB-APP
info:
  app:
    name: ${spring.application.name}
    version: 1.0
    description: "app"
app:
  pro:
    appkey: 00056cb1d74435076a4c15a490798df4
    path: /data/wwwroot/app/static/
    host: http://192.168.1.199:${server.port}/
  scheduler:
    enabled: false