server:
  port: 8081
spring:
  profiles:
    active: dev
  session: # session存储类型 NONE | REDIS | HASH_MAP
    store-type: HASH_MAP
  application:
    name: JFRAME-WEB-FRONT
management:
  security:
    enabled: false # 与spring security进行安全验证
  port: 9091 # 监控端口
  context-path: /monitor
  health: # 指定不监控服务
    mail:
      enabled: false
security: # spring security安全设置
  basic:
    enabled: false
    path: /monitor
  user:
    name: spring
    password: spring1234
endpoints: # Actuator监控，可自定义端点的开关-enabled
  enabled: true
  jmx:
    enabled: false
  beans:
    enabled: false
  mappings:
    enabled: false
  autoconfig:
    enabled: false
  configprops:
    enabled: false
  logfile:
    enabled: true
info: # 定义各种额外的详情给服务端显示
  app:
    name: ${spring.application.name}
    version: "1.0"
    description: "pc"
eureka: # eureka客户端注册
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka:eureka1234@127.0.0.1:10000/eureka/ # eureka服务端地址