server:
  port: 8081
spring:
  profiles:
    active: dev
  session: # session存储类型 NONE | REDIS
    store-type: none
  application:
    name: JFRAME-WEB-FRONT
  boot:
    admin:
      client:
        enabled: true
        prefer-ip: true # 解决windows下运行时无法识别主机名的问题
      url: http://127.0.0.1:10000
      api-path: sba/api/applications # 服务端注册的ip和地址
      username: eureka
      password: eureka1234
management:
  security:
    enabled: false # spring-boot 1.5.2之后严格执行安全策略
  #port: 9090
  context-path: /monitor
security: # spring安全设置
  basic: # 启用|关闭安全
    enabled: false
    path: /monitor # 需要配置安全的路径
  user: # 用户名和密码
    name: cloud
    password: cloud1234
endpoints: # 开启监控
  health:
    enabled: true
info: # 定义各种额外的详情给服务端显示
  app:
    name: ${spring.application.name}
    version: 1.0
eureka: # eureka客户端注册
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka:eureka1234@127.0.0.1:10000/eureka/ # eureka服务端地址
