server:
  port: 8081
spring:
  profiles:
    active: dev
    include: monitor # 使用监控配置
  session: # session存储类型 NONE | REDIS | HASH_MAP
    store-type: HASH_MAP
  application:
    name: JFRAME-WEB-FRONT
info: # 定义各种额外的详情给服务端显示
  app:
    name: ${spring.application.name}
    version: "1.0"
    description: "pc"
eureka: # eureka客户端注册
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka:eureka1234@127.0.0.1:10000/eureka/ # eureka服务端地址
feign: # 断路器
  hystrix:
    enabled: true
app: # 独立应用配置
  pro: # 生产环境专用
    appkey: ""
    path: /data/wwwroot/front/static/
    host: http://192.168.1.199:${server.port}/
  scheduler: # 定时任务开关
    enabled: false