server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: JFRAME-WEB-FRONT
info:
  app:
    name: ${spring.application.name}
    version: "1.0"
    description: "pc"
app:
  static_path: /data/wwwroot/front/static/
  static_host: http://192.168.1.200:8081/