# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://127.0.0.1:8081/test?name=fei&type=123
Accept: */*
Cache-Control: no-cache

###
POST http://127.0.0.1:8081/testError2
Accept: */*
Cache-Control: no-cache
X-Requested-With: XMLHttpRequest

<> 2018-05-23T053354.200.json

###
GET http://127.0.0.1:8082/app/token?param=1234
Accept: */*
Cache-Control: no-cache
Req-Type: APP
token: 4F88FA216F6EDEDE8230770EAAD56608

<> 2018-05-25T055124.200.json
<> 2018-05-25T055116.200.json

###
GET http://127.0.0.1:8082/app/get
Accept: */*
Cache-Control: no-cache
Req-Type: APP
X-Requested-With: XMLHttpRequest


########## OAuth2.0 ##########

###client模式?
POST http://127.0.0.1:8090/oauth/token?grant_type=client_credentials&scope=all&client_id=client&client_secret=123456
Accept: */*
Cache-Control: no-cache

<> 2018-06-07T053023.200.json
<> 2018-06-07T050505.200.json

###password模式
POST http://127.0.0.1:8090/oauth/token?username=spring&password=123456&grant_type=password&scope=all&client_id=pwd&client_secret=123456
Accept: */*
Cache-Control: no-cache

<> 2018-06-07T035521.200.json

###授权码模式 - 浏览器访问
POST http://127.0.0.1:8090/oauth/authorize?response_type=code&client_id=client&client_secret=123456&state=states
    &redirect_uri=http://www.baidu.com
Accept: */*
Cache-Control: no-cache

<> 2018-05-31T031242.403.json


###check_token
POST http://127.0.0.1:8090/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNTI4Mjc4MjI1LCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiYWI5M2QwMzAtNmI2YS00ZWIyLWE2YjItNmUyZDU0Mjg4MTZkIiwiY2xpZW50X2lkIjoiY2xpZW50In0.txBHn0uaN-5JC7yGNiVb9wA61LU5XCLb4Q8zkcPAF3w
Accept: */*
Cache-Control: no-cache

<> 2018-06-07T035526.400.json
<> 2018-06-07T102643.400.json

###auth server
POST http://127.0.0.1:8090/authentication/user?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNTI4MzY1MDIzLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiMWNhYzFlMTAtZDg5OC00OTRmLWI2MDAtZDAxYjhjNDk5Nzg3IiwiY2xpZW50X2lkIjoiY2xpZW50In0.CSHHDvZGh0Sc1PFoM8vV7dRG76MH-ct_qM2hVdOR7N4
Accept: */*
Cache-Control: no-cache

<> 2018-06-07T053048.200.json
<> 2018-06-07T035530.401.json

###
POST http://127.0.0.1:8090/hello?access_token=471d240b-7401-43e1-9d50-6e5ce5efdfcf
Accept: */*
Cache-Control: no-cache

###
GET http://127.0.0.1:8099/test
Accept: */*
Cache-Control: no-cache

<> 2018-06-07T053722.200.txt
<> 2018-06-07T093837.200.txt
<> 2018-06-07T093812.200.txt

###
GET http://127.0.0.1:8888/testLog
Accept: */*
Cache-Control: no-cache

###