# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

########## OAuth2.0 ##########

###client模式
POST {{host}}/oauth/token?grant_type=client_credentials&scope=all&client_id=client&client_secret=123456
Accept: */*
Cache-Control: no-cache

###password模式
POST {{host}}/oauth/token?grant_type=password&scope=all&client_id=pwd&client_secret=123456&username=17730215423&password=123456
Accept: */*
Cache-Control: no-cache

###授权码模式 - 浏览器访问
POST {{host}}/oauth/authorize?client_id=sso01&client_secret=123456&response_type=code&state=states&redirect_uri=http://www.baidu.com
Accept: */*
Cache-Control: no-cache


###check_token
POST {{host}}/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjcwODgwODQsInVzZXJfbmFtZSI6InRlc3QiLCJhdXRob3JpdGllcyI6WyJVU0VSIl0sImp0aSI6ImM1YWViZTFlLTAyNTMtNGJkNy1iNjQyLWM2NzhkZTg0YzI4MiIsImNsaWVudF9pZCI6InNzbzAxIiwic2NvcGUiOlsiYWxsIl19.YvPYtSYfM5MRATyWNFouQAauKXnMlYjTA1Wipqyk4_8
Accept: */*
Cache-Control: no-cache

###auth server
POST {{host}}/authentication/user?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjcwODgwODQsInVzZXJfbmFtZSI6InRlc3QiLCJhdXRob3JpdGllcyI6WyJVU0VSIl0sImp0aSI6ImM1YWViZTFlLTAyNTMtNGJkNy1iNjQyLWM2NzhkZTg0YzI4MiIsImNsaWVudF9pZCI6InNzbzAxIiwic2NvcGUiOlsiYWxsIl19.YvPYtSYfM5MRATyWNFouQAauKXnMlYjTA1Wipqyk4_8
Accept: */*
Cache-Control: no-cache

###
#POST {{host}}/hello?access_token=471d240b-7401-43e1-9d50-6e5ce5efdfcf
#Accept: */*
#Cache-Control: no-cache

###
GET {{host}}/oauth/token_key
Accept: */*
Cache-Control: no-cache