server:
  port: 8084
spring:
  rabbitmq:
    host: dev # 服务器地址
    port: 5672
    username: rabbitmq
    password: 12345678
    virtual-host: /rmq-d # 虚拟Host,需要预先创建 '/hostname'并设置权限
    requested-heartbeat: 10s
    listener:
      simple:
        acknowledge-mode: manual # 开启ACK
        concurrency: 2 # 消费者数量
        prefetch: 10 # 每个消费者获取最大投递数量
        retry: # 是否支持重试
          enabled: true
          initial-interval: 10s
          max-attempts: 10