logging:
  config: classpath:logback-boot.xml # 日志配置文件
server:
  tomcat: # tomcat容器
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 20
    max-connections: 2000
  undertow: # undertow容器
    io-threads: 4 # 设置IO线程数，主要执行非阻塞的任务,负责多个连接，默认设置每个CPU核心一个线程
    worker-threads: 20 # 阻塞任务线程池, 执行类似servlet请求阻塞IO操作，默认是IO线程数*8
    buffer-size: 1024 # 用于服务器连接的IO操作，越小的空间被利用越充分
    direct-buffers: true # 是否分配的直接内存(NIO直接分配的堆外内存)
  servlet:
    session:
      timeout: 30m # session过期时间
#      cookie:
#        name: SESSIONID
#    context-path:
#  ssl:
#    enabled: false
#    key-store: classpath:test.jks
#    key-store-type: JKS
#    key-password: 123456
spring:
  jmx:
    enabled: true
  cache: # 缓存设置
    type: REDIS # 缓存类型 NONE | REDIS
    cache-names: user,order # 缓存的名称(多个)
    redis:
      time-to-live: 20m
  session: # session存储类型 NONE | REDIS
    store-type: NONE
  mvc:
    static-path-pattern: /static/** # 静态地址映射
  servlet:
    multipart: # 文件上传限制
      max-file-size: 50MB
      max-request-size: 10MB
  resources:
    static-locations: classpath:/static/,file:${system.static_path} # 静态文件目录
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # json时间转换
    time-zone: GMT+8
    default-property-inclusion: non_null # json空不输出
  freemarker:
    template-loader-path: classpath:/templates # 模板文件目录
    cache: true # 缓存
    charset: UTF-8
    settings: # 数据格式设置
      template_update_delay: 0
      default_encoding: UTF-8
      locale: zh_CN
      url_escaping_charset: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##
      boolean_format: true,false
      classic_compatible: true
      whitespace_stripping: true
  datasource:
    druid: # Druid数据源配置
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/jframe?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 12345678
      initial-size: 5 # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      max-active: 20 # 最大连接池数量 Default:8
      max-wait: 60000 # 获取连接时最大等待时间
      min-idle: 5 # 最小连接池数量
      time-between-eviction-runs-millis: 60000 # 1.Destroy线程会检测连接的间隔时间 2.test-while-idle的判断依据
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 # 用来检测连接是否有效的sql，要求是一个查询语句
      max-open-prepared-statements: 20 # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      remove-abandoned: true # 连接使用超过时间限制是否回收
      remove-abandoned-timeout-millis: 60000 # 超过时间限制时间（s）,Default:300s
      test-on-borrow: false # 申请连接时执行validationQuery检测连接是否有效,会降低性能
      test-on-return: false # 归还连接时执行validationQuery检测连接是否有效,会降低性能
      test-while-idle: true # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      filter: # 自定义StatFilter配置
        stat:
          enabled: ${app.druid.enabled:false}
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      stat-view-servlet: # Druid监控配置
        enabled: ${app.druid.enabled:false}
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: ${app.druid.enabled:false}
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.woff,/druid/*"
      aop-patterns: com.jf.service.* # Spring监控AOP切入点
  aop:
    proxy-target-class: true # 开启AOP，使用CGLIB代理
  task: # 线程池设置
    corePoolSize: 10 # 维护线程的最少数量
    maxPoolSize: 30 # 线程池最大的线程数，只有在缓冲队列满了之后才会申请超过核心线程数的线程
    queueCapacity: 200 # 线程池所使用的缓冲队列
    keepAliveSeconds: 60 # 维护线程所允许的空闲时间
    waitOnShutdown: true # 设置线程池关闭的时候等待所有任务都完成再继续销毁其他的Bean
    awaitTerminationSeconds: 60 # 设置线程池中任务的等待时间，如果超过这个时候还没有销毁就强制销毁
  mail: # 邮件服务器设置
    host: smtp.qq.com
    username: 1@qq.com
    password: 1
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          timeout: 25000
  redis: # spring redis
    host: 192.168.24.200
    port: 6379
    password:  # 密码
    timeout: 5s
    lettuce: # 使用lettuce或者jedis
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 10
#    sentinel: # Sentinel集群
#      master: mymaster
#      nodes:
#        - 192.168.1.199:26379
#        - 192.168.1.199:26380
#    cluster: # Cluster集群(6)
#      nodes:
#        - 192.168.1.199:7001
#        - 192.168.1.199:7002
#        - 192.168.1.199:7003
#        - 192.168.1.199:7004
#        - 192.168.1.199:7005
#        - 192.168.1.199:7006
  activemq: # activemq[弃用]
    broker-url: tcp://192.168.1.199:61616 # 服务器地址
    in-memory: true
    pool:
      enabled: false # 如果此处设置为true，需要加依赖包:org.apache.activemq > activemq-pool
    user: activemq
    password: 12345678
    packages:
      trust-all: true
  rabbitmq: # rabbitmq
    host: 192.168.24.200 # 服务器地址
    port: 5672
    username: rabbitmq
    password: 12345678
    virtual-host: /rmq2 # 虚拟Host,需要预先创建 '/hostname'并设置权限
    requested-heartbeat: 10s
    publisher-confirms: true # 开启发送确认
    publisher-returns: true # 开启发送失败退回
    listener:
      simple:
        acknowledge-mode: manual # 开启ACK
        concurrency: 10 # 消费者数量
        prefetch: 50 # 每个消费者获取最大投递数量
        retry: # 是否支持重试
          enabled: true
          initial-interval: 10s
          max-attempts: 3
  quartz: # quartz配置
    job-store-type: memory # jdbc | memory
    properties: # Quartz属性配置
      org:
        quartz:
          scheduler:
            instanceName: DefaultQuartzScheduler
            instanceId: AUTO
          #jobStore: # jdbc支持(需先导入SQL)
            #class: org.quartz.impl.jdbcjobstore.JobStoreTX
            #driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            #tablePrefix: qz_
            #isClustered: true
            #clusterCheckinInterval: 10000
            #useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10 # 并发数
            threadPriority: 5 # 优先级
            threadsInheritContextClassLoaderOfInitializingThread: true
fdfs: # fastDFS配置
  so-timeout: 3000
  connect_timeout: 3000
  tracker-list: # 可设置多个
    - 192.168.1.199:22122
system: # 系统自定义配置
  version: 'v5.2'
  dev: true # 是否开发环境
  appkey: ${app.appkey:0}
  static_host: http://127.0.0.1:${server.port}/ # 静态服务器地址
  static_path: /Users/xujunfei/Downloads/static/ # 静态文件目录
  log_path: /Users/xujunfei/Downloads/logs/ # 日志存放目录
  server_id: ${spring.application.name}
  fdfs_nginx: http://192.168.1.199/ # DFS Nginx代理服务器地址
  aliyun: # 支付宝
    partner: 2088
    seller: nf@sandbox.com
    app_id: 2016
    rsa_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCAbqwHTigw8Bs0czuAwy4Y8zyqdIhzVCMn9H4/oBF0J+t2eTxlAUCuXjX/vrf+X2bGVMiCym54s1IGQ3Himaon30thys4FxM7QVvH6UC6OefZLkaG1i4mpvYUK3gzsT+PHqbpK/lkQ6RoYwg3mHSHSl2Td/08SIJ326W8Ujs29YOID2OzUusupSly+acdHVwf/IRiuP9FkL/f0e9jwUzGTMhTuP2DXWU9frd0D2n9DHL+BL3kmQm2NToAJ+2xvhiqI5nPixQxe9ua38N2i3xMNY5N2/6nCmvpj7UZzVWdYkcmNQLPNvUeLNbohX4U/R+HYZ1SeTiIgIaog9nX6ctW3AgMBAAECggEAKOSUK8NL8sEQuHOUV5xN2i3gfBmctLPuebNUW2fZBtYLF+7kNvjeImbm5KZSKVExBSdLrLFN2WqnTE0/PrpUvltPwjRzwsx2WUnFxECxgjX9IPSeu5JRY9VvPhWToc6SJSm6olQ4AbVm1Mk86a8O7OG9gR3gjFIMWejbsH0Dry9qtsSD4byYuLXwQ/yy7CC9ZV/v76veCBwZxYiG1LzRLn82qCl5B3QwTj1K7wyGpYE2OHflTDBe05H82eUpnbUb1xKt8y7TdquJWheInDDxvt7OthHFwNVJhp7zui9s580WiXP6DtrEtmINaYYHDgOGR2SmleygXloNIUQ02xSZAQKBgQDhMMobbS67dqMQ5JzYvErj8xbhVhSk3wiKm7+MBpCtpM40HNLy5Z82JqlngN6CkJdHBybqWmvDjER07MvzKjX3VuyYM/jFkuyOCpBHzjbXSnFk7xn5UKqlQFKoW5v8XJB8qwksxpBlvHNmFedwVMU0mOfDD4uoF1axEt7cDs5+NwKBgQCSAPZrv07KVs/eEFU+nqGu9UpmQ0D6ZITgEiDoQwPecSO2uKovY8TsCKYgfTAntY2oJ51Jqf6lV8cKr6Fm6CoWm687BT4E5gljoyWj7iGgt/WPhki+ocWcQkGbkFGN7wNel56+3/TCrnKWcgNqoh8BqpaMERT23QCqLdaNy8akgQKBgBGCobSQQNoC15swq6GOwqQG+vh6oRBQ53Efuz1AJW/bKM2UkDKi+EZVq0aJFsRASgMT40rFzStfdNNCtnkqBxg8ghkzsVxrmElTOPTcbBdBip+2l+ZzB1HiNosw1GhDKlkHU6dPqVq/1JlTirOJY+w7F4prYwinB+6s8Pdbj2LxAoGANFXr/wuAbr9Xm743EE9EnbaHiMiqzhaiGr/k09zR0ja0GpdvSbV1rTYcdqDpVhKaSKCKnRE2moYwbwAt1vl5vMjpszpZ1N+wleqxX2XI4BeRCnWUNeE/OJf3dI/y6/G1P38SBFG7Jt3pbUxJNTwP6UUA2gx1e1gVGOt9cS6OcgECgYEAvxHdlmsyMWU0dZmXA6Pgs4Nl4JE7gVuVkuo9eXVIEtM7Er6uopkmvQItvb0Jp7aCDZi/eblGS7HiFoxh5YFIO9AGzWgMbDPjBbFcaD2+ucqG/0FYqi4pNV3NX4PuEEAyywH9L8G/pv/WwfYBMckwvwtqh6wdf7HgYuLXgVXuduA=
    public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2F1OBxmr8/7Dd+uPMQoTzqJdldBG31c5YE8EpIdk+pxwyM0BGMXV1SETynt1br7Pw8MKOC+oJOTxD9hcqx7OOhsZhiqFH2iL5F4ejK9VNEPDxjwkZXjgYqnacK5cFRWq6iMn4tw5xTsxa1sSNtEoxjK4AZnpgTiTTT2hlB2TN6e78zW2ZMeyZ+ocb9jy5oa/xqMAv1Srgp2PIa1dQ5qDp52xxzs6PxjTZJwTh6v+Z2zJJaBu2lzkk/cY4LAYAkr2rxKRVseT4Xt5m8zRVA62rDlTd1/D7MoCS9ybGQ8IaGe/8XM+3FJtNjk1JKk6OQa2YWHgzqZz+BQQSZzeSGFn4QIDAQAB
    notify_url: http://xjf.s1.natapp.cc/alipay_callback
    return_url: http://xjf.s1.natapp.cc/alipay_return
    gateway: https://openapi.alipaydev.com/gateway.do
  wechat: # 微信
    appid: wx47
    partner: 1482
    partner_key: ad8b6
    notify_url: http://xjf.s1.natapp.cc/wxpay_callback
  geetest: # 极验验证
    id: a53178
    key: 51dbc8
  jpush: # jpush推送
    appkey: appkey
    secret: secret
    ios_product: false
  upload: # FastDFS
    fdfs: ${app.fdfs.enabled:false}
    img_size: 3
    img_type: jpg,jpeg,png
    file_size: 10
    file_type: zip,rar,txt