logging:
  config: classpath:logback-boot.xml # 日志配置文件
server:
  port: 8080 # 默认端口号
  connection-timeout: 5000
  tomcat: # tomcat容器
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 20
    max-connections: 2000
  undertow: # undertow容器
    io-threads: 4 # 设置IO线程数，主要执行非阻塞的任务,负责多个连接，默认设置每个CPU核心一个线程
    worker-threads: 20 # 阻塞任务线程池, 执行类似servlet请求阻塞IO操作，默认是IO线程数*8
    buffer-size: 1024 # 用于服务器连接的IO操作，越小的空间被利用越充分
    direct-buffers: true # 是否分配的直接内存(NIO直接分配的堆外内存)
  servlet:
    session:
      timeout: 30m # session过期时间
#      cookie:
#        name: SESSIONID
#    context-path:
#  ssl: # 不推荐使用，Nginx替代
#    enabled: false
#    key-store: classpath:test.jks
#    key-store-type: JKS
#    key-password: 123456
spring:
  profiles:
    active: app-dev # 指定应用和环境 {0}-{1}  0：表示应用，1：表示环境(固定：dev、test、pro)
  application:
    name: JFRAME-APP
    simple: app
  jmx:
    enabled: true
  cache: # 缓存设置
    type: REDIS # 缓存类型 NONE | REDIS
    cache-names: user,order # 缓存的名称(多个)
    redis:
      time-to-live: 20m
  session: # session存储类型 NONE | REDIS
    store-type: REDIS
    redis:
      namespace: spring:sessions # 命名空间
  mvc:
    static-path-pattern: /static/** # 静态地址映射
  servlet:
    multipart: # 文件上传限制
      max-file-size: 50MB
      max-request-size: 10MB
  resources:
    static-locations: classpath:/static/,file:${system.static_path} # 静态文件目录
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # json时间转换
    time-zone: GMT+8
    default-property-inclusion: non_null # json空不输出
  freemarker:
    template-loader-path: classpath:/templates # 模板文件目录
    cache: true # 缓存
    charset: UTF-8
    settings: # 数据格式设置
      template_update_delay: 0
      default_encoding: UTF-8
      locale: zh_CN
      url_escaping_charset: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##
      boolean_format: true,false
      classic_compatible: true
      whitespace_stripping: true
  datasource:
    druid: # Druid数据源配置
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://dev:3306/jframe?useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 12345678
      initial-size: 5 # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      max-active: 20 # 最大连接池数量 Default:8
      max-wait: 60000 # 获取连接时最大等待时间
      min-idle: 5 # 最小连接池数量
      time-between-eviction-runs-millis: 60000 # 1.Destroy线程会检测连接的间隔时间 2.test-while-idle的判断依据
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 # 用来检测连接是否有效的sql，要求是一个查询语句
      max-open-prepared-statements: 20 # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      remove-abandoned: true # 连接使用超过时间限制是否回收
      remove-abandoned-timeout-millis: 60000 # 超过时间限制时间（s）,Default:300s
      test-on-borrow: false # 申请连接时执行validationQuery检测连接是否有效,会降低性能
      test-on-return: false # 归还连接时执行validationQuery检测连接是否有效,会降低性能
      test-while-idle: true # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      filter: # 自定义StatFilter配置
        stat:
          enabled: false
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      stat-view-servlet: # Druid监控配置
        enabled: false
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 1ead34fjf48adsjvnm323
      web-stat-filter:
        enabled: false
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.woff,/druid/*"
      aop-patterns: com.jf.service.* # Spring监控AOP切入点
  aop:
    proxy-target-class: true # 开启AOP，使用CGLIB代理
  task: # 线程池设置
    corePoolSize: 10 # 维护线程的最少数量
    maxPoolSize: 30 # 线程池最大的线程数，只有在缓冲队列满了之后才会申请超过核心线程数的线程
    queueCapacity: 200 # 线程池所使用的缓冲队列
    keepAliveSeconds: 60 # 维护线程所允许的空闲时间
    waitOnShutdown: true # 设置线程池关闭的时候等待所有任务都完成再继续销毁其他的Bean
    awaitTerminationSeconds: 60 # 设置线程池中任务的等待时间，如果超过这个时候还没有销毁就强制销毁
  mail: # 邮件服务器设置
    host: smtp.163.com
    username: xxx@163.com
    password: xxx
    port: 994
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          timeout: 25000
  redis: # spring redis
    host: dev
    port: 6379
    password:  # 密码
    timeout: 5s
    lettuce: # 使用lettuce或者jedis
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 10
  #    sentinel: # Sentinel集群
  #      master: mymaster
  #      nodes:
  #        - 192.168.1.168:26379
  #        - 192.168.1.168:26380
  #    cluster: # Cluster集群(6)
  #      nodes:
  #        - 192.168.1.168:7001
  #        - 192.168.1.168:7002
  #        - 192.168.1.168:7003
  #        - 192.168.1.168:7004
  #        - 192.168.1.168:7005
  #        - 192.168.1.168:7006
  rabbitmq: # rabbitmq
    host: dev # 服务器地址
    port: 5672
    username: rabbitmq
    password: 12345678
    virtual-host: /rmq # 虚拟Host,需要预先创建 '/hostname'并设置权限
    requested-heartbeat: 10s
    publisher-confirms: true # 开启发送确认
    publisher-returns: true # 开启发送失败退回
    listener:
      simple:
        acknowledge-mode: manual # 开启ACK
        concurrency: 10 # 消费者数量
        prefetch: 50 # 每个消费者获取最大投递数量
        retry: # 是否支持重试
          enabled: true
          initial-interval: 10s
          max-attempts: 3
  #    cache:
  #      channel:
  #        size: 100
  quartz: # quartz配置
    job-store-type: jdbc # jdbc | memory
    properties: # Quartz属性配置
      org:
        quartz:
          scheduler:
            instanceName: DefaultQuartzScheduler
            instanceId: AUTO
          jobStore: # jdbc支持(需先导入SQL)
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qz_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10 # 并发数
            threadPriority: 5 # 优先级
            threadsInheritContextClassLoaderOfInitializingThread: true
# 应用信息
info:
  app:
    name: ${spring.application.name}
    version: "1"
    description: ${spring.application.name}
# springcloud config support
eureka: # eureka客户端注册
  client:
    enabled: ${app.eureka.enabled:false}
    serviceUrl:
      defaultZone: http://eureka:eureka1234@127.0.0.1:10000/eureka/ # eureka服务端地址
feign: # 断路器|监控 需配合注解使用*
  hystrix:
    enabled: ${app.eureka.enabled:false}
management:
  endpoints: # Actuator监控
    enabled-by-default: ${app.monitor.enabled:false}
    web:
      base-path: /monitor # 监控主路径
      exposure: # 暴露的接口
        include: info, health, env, httptrace, metrics, threaddump, logfile, refresh
    jmx:
      exposure:
        include: info, health, mappings, beans # 不暴露jmx: exclude: '*'
  server:
    add-application-context-header: false # 隐藏http头
  endpoint:
    health: # 显示详细
      show-details: ALWAYS
  health: # 指定不监控的服务
    mail:
      enabled: false
    jms:
      enabled: false
fdfs: # fastDFS配置
  so-timeout: 3000
  connect_timeout: 3000
  tracker-list: # 可设置多个
    - 192.168.31.205:22122
system: # 系统自定义配置
  version: 'v5.7'
  dev: true # 是否开发环境
  appkey: 00056cb1d74435076a4c15a490798df4 # APP访问校验码
  static_host: http://127.0.0.1:${server.port}/ # 静态服务器地址，如果配置了FASTDFS，此项可以不用配置
  static_path: /Users/xujunfei/Downloads/tmp/static/ # 静态文件目录
  log_path: /Users/xujunfei/Downloads/tmp/logs/ # 日志存放目录
  server_id: ${spring.application.name} # 服务ID，用于日志标记
  fdfs_nginx: http://192.168.1.168/ # DFS Nginx代理服务器地址
  alipay: # 支付宝
    partner: 2088
    seller: nf@sandbox.com
    app_id: 2016
    rsa_private_key: xxx
    public_key: xxx
    notify_url: http://xxx/alipay_callback
    return_url: http://xxx/alipay_return
    gateway: https://openapi.alipaydev.com/gateway.do
  aliyun: # 阿里云
    access_id: xxx
    access_secret: xxx
  wechat: # 微信支付
    appid: wx47
    partner: 1482
    partner_key: xxx
    notify_url: http://xxx/wxpay_callback
    mp_id: xxx  # 微信公众号
    mp_key: xxx
  geetest: # 极验验证
    id: a53178
    key: 51dbc8
  jpush: # jpush推送
    name: xxx
    appkey: appkey
    secret: secret
    ios_product: false
  upload: # FastDFS
    fdfs: true
    img_size: 3
    img_type: jpg,jpeg,png
    file_size: 10
    file_type: zip,rar,txt

# 环境配置说明：
# 1、spring.profiles.active必须严格按照注释命名
# 2、spring.application.simple为应用简称，必须指定，否则日志不生效
# 3、生产环境务必配置好静态文件路径和URL前缀、日志路径、数据库等，开发环境可以使用`默认`不配置
# 4、可复写以上公共配置
# 5、环境指定：spring.profiles.active=app-dev


##################### 后台管理端 开发 #####################
---
spring:
  profiles: manage-dev
  application:
    name: JFRAME-WEB-MANAGE
    simple: manage
server:
  port: 8080
app:
  async:
    enabled: true

##################### 后台管理端 生产 #####################
---
spring:
  profiles: manage-pro
  application:
    name: JFRAME-WEB-MANAGE
    simple: manage
server:
  port: 18080
system:
  static_path: /data/wwwroot/manage/static/
  static_host: http://192.168.1.168:${server.port}/
  log_path: /data/wwwlogs/

##################### PC端 开发 #####################
---
spring:
  profiles: front-dev
  application:
    name: JFRAME-WEB-FRONT
    simple: front
server:
  port: 8081

##################### PC端 生产 #####################
---
spring:
  profiles: front-pro
  application:
    name: JFRAME-WEB-FRONT
    simple: front
server:
  port: 18081
system:
  static_path: /data/wwwroot/front/static/
  static_host: http://192.168.1.168:${server.port}/
  log_path: /data/wwwlogs/

##################### APP端 开发 #####################
---
spring:
  profiles: app-dev
  application:
    name: JFRAME-WEB-APP
    simple: app
server:
  port: 8082
app:
  cache:
    enabled: true

##################### APP端 生产 #####################
---
spring:
  profiles: app-pro
  application:
    name: JFRAME-WEB-APP
    simple: app
server:
  port: 18082
system:
  static_path: /data/wwwroot/app/static/
  static_host: http://192.168.1.168:${server.port}/
  log_path: /data/wwwlogs/

###################### 综合测试 #####################
---
spring:
  profiles: test-dev
  application:
    name: JFRAME-WEB-TEST
    simple: test
server:
  port: 8888
  servlet:
    session:
      cookie:
        name: JSAUID
app:
  eureka: # Eureka注册服务
    enabled: false
  monitor: # 监控端点
    enabled: false
  cache: # redis缓存支持
    enabled: true
  ssl: # 启用SSL
    enabled: false
rmi: # 启用rmi监控
  enabled: false
  host: 127.0.0.1
  port: ${server.port}
wx: # 微信公众号API
  appid: 111111
  token: qwertyuiopqwertyuiopqwertyuiopqw
  appsecret: 111111
  callback-url:

##################### 微服务测试 #####################
---
spring:
  profiles: srvtest-dev
  application:
    name: JFRAME-SRV-ORDER-01
    simple: srvtest
  zipkin:
    base-url: http://192.168.24.200:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 10003
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:8090/authentication/user
app:
  eureka:
    enabled: true
  monitor:
    enabled: true