# springcloud config support
spring:
  security: # spring security
    user:
      name: spring
      password: $2a$10$2l13OXNHQVWVoaJTeoabtuxROniihnqThG/MB8aItx3Er540PDTWe
      roles: ACTUATOR
eureka: # eureka客户端注册
  client:
    enabled: ${app.eureka.enabled:false}
    serviceUrl:
      defaultZone: http://eureka:eureka1234@127.0.0.1:10000/eureka/ # eureka服务端地址
feign: # 断路器|监控 需配合注解使用*
  hystrix:
    enabled: ${app.eureka.enabled:false}
management:
  endpoints: # Actuator监控
    enabled-by-default: ${app.monitor.enabled:false}
    web:
      base-path: /monitor # 监控主路径
      exposure: # 暴露的接口
        include: info, health, env, httptrace, metrics, threaddump, logfile, refresh
    jmx:
      exposure:
        include: info, health, mappings, beans # 不暴露jmx: exclude: '*'
  server:
    add-application-context-header: false # 隐藏http头
  endpoint:
    health: # 显示详细
      show-details: WHEN_AUTHORIZED
  health: # 指定不监控的服务
    mail:
      enabled: false
    jms:
      enabled: false