logging:
  config: classpath:logback-boot.xml
  #file: ${system.log_path}${app.name:jframe}.log
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 20
    max-connections: 2000
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true
  servlet:
    session:
      timeout: 30m
  ssl:
    enabled: ${app.ssl.enabled:false}
    key-store: classpath:test.jks
    key-store-type: JKS
    key-password: 123456
spring:
  jmx:
    enabled: false
  cache:
    type: NONE
    cache-names: user,order
    redis:
      time-to-live: 20m
  session:
    store-type: NONE
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 10MB
  resources:
    static-locations: classpath:/static/,file:${system.static_path}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  freemarker:
    template-loader-path: classpath:/templates
    cache: true
    charset: UTF-8
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      locale: zh_CN
      url_escaping_charset: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##
      boolean_format: true,false
      classic_compatible: true
      whitespace_stripping: true
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://mysql:3306/jframe?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 12345678
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      max-open-prepared-statements: 20
      remove-abandoned: true
      remove-abandoned-timeout-millis: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filter:
        stat:
          enabled: ${app.druid.enabled:false}
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      stat-view-servlet:
        enabled: ${app.druid.enabled:false}
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 1ead34fjf48adsjvnm323
      web-stat-filter:
        enabled: ${app.druid.enabled:false}
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.woff,/druid/*"
      aop-patterns: com.jf.service.*
  aop:
    proxy-target-class: true
  task:
    corePoolSize: 10
    maxPoolSize: 30
    queueCapacity: 200
    keepAliveSeconds: 60
    waitOnShutdown: true
    awaitTerminationSeconds: 60
  mail:
    host: smtp.qq.com
    username: 1@qq.com
    password: 1
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          timeout: 25000
  redis:
    host: redis
    port: 6379
    password:
    timeout: 5s
    lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 10
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rabbitmq
    password: 12345678
    virtual-host: /rmq2
    requested-heartbeat: 10s
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 10
        prefetch: 50
        retry:
          enabled: true
          initial-interval: 10s
          max-attempts: 3
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          scheduler:
            instanceName: DefaultQuartzScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
fdfs:
  so-timeout: 3000
  connect_timeout: 3000
  tracker-list:
    - fdfs:22122
system:
  version: 'v5'
  dev: false
  appkey: ${app.appkey:0}
  static_host: ${app.static_host}
  static_path: ${app.static_path}
  log_path: /data/wwwlogs/
  server_id: ${spring.application.name}
  fdfs_nginx: http://192.168.1.199/
  aliyun:
    partner: 2088
    seller: nf@sandbox.com
    app_id: 2016
    rsa_private_key: xxx
    public_key: xxx
    notify_url: http://xxx/alipay_callback
    return_url: http://xxx/alipay_return
    gateway: https://openapi.alipay.com/gateway.do
  wechat:
    appid: wx47
    partner: 1482
    partner_key: xxx
    notify_url: http://xxx/wxpay_callback
  geetest:
    id: a53178
    key: 51dbc8
  jpush:
    name: xxx
    appkey: appkey
    secret: secret
    ios_product: false
  upload:
    fdfs: ${app.fdfs.enabled:false}
    img_size: 3
    img_type: jpg,jpeg,png
    file_size: 10
    file_type: zip,rar,txt