server:
  port: 8888
spring:
  profiles:
    active: dev
    include: cloud # 加载springcloud配置
  application:
    name: JFRAME-WEB-TEST
info: # 定义各种额外的详情给服务端显示
  app:
    name: ${spring.application.name}
    version: "1.0"
    description: "pc"
# ↓↓↓↓↓↓ 独立应用配置
# 如果值false，可以不配置
# enabled值仅用于条件加载各个组件
app:
  host: 192.168.1.199 # 生产环境服务器地址（用于文件上传返回绝对路径↓↓↓）
  static_path: /data/wwwroot/test/static/ # 静态文件目录
  static_host: http://${app.host}:${server.port}/ # 静态文件地址
  secondb: # 从或备数据库
    enabled: false
  eureka: # Eureka注册服务
    enabled: false
  monitor: # 监控端点
    enabled: true
  druid: # druid数据源监控
    enabled: false
  springsch: # spring定时器
    enabled: false
  quartz: # Quartz定时任务
    enabled: true
  cache: # redis缓存支持
    enabled: true
  redisson: # 分布式锁
    enabled: false
  activemq: # ActiveMQ
    enabled: false
  rabbitmq: # RabbitMQ
    enabled: false
  socket: # spring websocket
    enabled: false
  fdfs: # FastDFS,false则使用本地上传
    enabled: false
rmi: # 启用rmi监控
  enabled: true
  host: 127.0.0.1
  port: ${server.port}
wx: # 微信公众号API
  appid: 111111
  token: qwertyuiopqwertyuiopqwertyuiopqw
  appsecret: 111111
  callback-url: