server:
  port: 8888
spring:
  profiles:
    active: dev
  application:
    name: JFRAME-WEB-TEST
info: # 定义各种额外的详情给服务端显示
  app:
    name: ${spring.application.name}
    version: "1.0"
    description: "pc"
# ↓↓↓↓↓↓ 独立应用配置
# 如果值false，可以不配置
# 在dev/pro环境有调用，有默认值
# *注：springcloud相关的jar在各个端的pom下
app:
  pro: # 生产环境专用
    appkey: ""
    static_path: /data/wwwroot/test/static/
    static_host: http://192.168.1.199:${server.port}/
  db: # 多数据库 -可同时启用,但必须启用一个*
    db1:
      enabled: true
    db2:
      enabled: false
  eureka: # Eureka注册服务
    enabled: false
  monitor: # 监控端点 为true需引用monitor配置*
    enabled: true
  druid: # druid数据源监控
    enabled: true
  springsch: # spring定时器
    enabled: false
  redisson: # 分布式事务
    enabled: false
  activemq: # ActiveMQ
    enabled: false
  socket: # spring websocket
    enabled: false
  fdfs: # FastDFS,false则使用本地上传
    enabled: false