spring:
  datasource:
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.24.200:5432/jframe?currentSchema=
      username: postgres
      password: 12345678
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      max-open-prepared-statements: 20
      remove-abandoned: true
      remove-abandoned-timeout-millis: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      filter:
        stat:
          enabled: ${app.druid.enabled:false}
          db-type: postgresql
          log-slow-sql: true
          slow-sql-millis: 2000
      stat-view-servlet:
        enabled: ${app.druid.enabled:false}
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 1ead34fjf48adsjvnm323
      web-stat-filter:
        enabled: ${app.druid.enabled:false}
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,*.woff,/druid/*"
      aop-patterns: com.jf.service.*