server:
  port: 10002
spring:
  profiles:
    active: dev
  application:
    name: JFRAME-SRV-ORDER-01
info:
  app:
    name: ${spring.application.name}
    version: "1.0"
    description: "service-order-01"
app:
  eureka:
    enabled: true
  monitor:
    enabled: true
  db:
    primary:
      enabled: true