server:
  port: 10003
spring:
  profiles:
    active: dev
    include: cloud
  application:
    name: JFRAME-SRV-ORDER-01
info:
  app:
    name: ${spring.application.name}
    version: "1.0"
    description: "service-order-01"
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:8090/authentication/user
app:
  eureka:
    enabled: true
  monitor:
    enabled: true